language : node_js
node_js:
  - stable

branches:
  only:
    - master

before_script:
  - npm install -g firebase-tools
  - npm install -g @angular/cli

script:
  - ng build --prod --env=prod -pr=false

after_success:
 - firebase deploy --non-interactive --token $FIREBASE_API_TOKEN

notifications:
  email:
    on_failure: change
    on_success: change
