language : node_js
node_js:
  - stable

branches:
  only:
    - master

before_script:
  - npm install -g firebase-tools
  - npm install -g @angular/cli

script:
  - ng build --prod

after_sucess:
 - firebase deploy --token=${FIREBASE_API_TOKEN}

notifications:
  email:
    on_failure: change
    on_success: change
